### ISSUE TITLE
Symmetry Issue for Infinite Point Groups

### ISSUE THREAD

**Issue by vogden** [schuurman-group/graci#35]
GRaCI fails when setting use_sym = True for linear molecules and atoms 

**ex. GRaCI input file:**
[cyanogen_dftmrci.txt](https://github.com/schuurman-group/graci/files/8912871/cyanogen_dftmrci.txt)

**error message:**
```
Traceback (most recent call last):
  File "/software/graci/bin/graci", line 62, in <module>
    main()
  File "/software/graci/graci/utils/timing.py", line 26, in __call__
    self.func.__name__, *args, **kwargs)
  File "/software/graci/graci/utils/timing.py", line 36, in _run_func
    result = self.func(*args, **kwargs)
  File "/software/graci/bin/graci", line 29, in main
    graci_driver.run(obj_array)
  File "/software/graci/graci/core/driver.py", line 56, in run
    mol_obj.run()
  File "/software/graci/graci/core/molecule.py", line 131, in run
    self.sym_indx = point_grps.index(self.comp_sym)
ValueError: 'dooh' is not in list
```

**Comment by spneville** [comment]
Fixed
